# Generated by Django 4.0.6 on 2022-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_description_for_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
