# Generated by Django 4.0.6 on 2022-07-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_description_for_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='default_description_for_items.genre', verbose_name='Genre'),
        ),
    ]
