# Generated by Django 4.0.6 on 2022-07-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_description_for_items', '0002_author_delete_autor_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Genre'),
        ),
    ]
