# Generated by Django 4.0.6 on 2022-08-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Postcode'),
        ),
    ]
