# Generated by Django 4.0.6 on 2022-08-12 23:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_deliveryaddress_postcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country/Region'),
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Postcode'),
        ),
    ]
