# Generated by Django 4.0.6 on 2022-07-28 23:17

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('default_description_for_items', '0002_author_delete_autor_alter_genre_name'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name of the item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price(BYN)')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Release year')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='Print lenght (pages)')),
                ('cover', models.CharField(choices=[('Hard', 'Hardcover'), ('Soft', 'Paperback')], max_length=30, verbose_name='Book type')),
                ('dimensions', models.CharField(max_length=25, verbose_name='Dimensions')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Item weight(gram)')),
                ('instock', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=30, verbose_name='In stock')),
                ('age', models.CharField(max_length=3, verbose_name='Reading Age')),
                ('availible', models.PositiveIntegerField(verbose_name='Books available')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating (0-10)')),
                ('cataloging_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of cataloging')),
                ('changing_date', models.DateTimeField(auto_now=True, verbose_name='Changing date')),
                ('author', models.ManyToManyField(related_name='authors', to='default_description_for_items.author', verbose_name='Authors')),
                ('genre', models.ManyToManyField(related_name='genres', to='default_description_for_items.genre', verbose_name='Genres')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishers', to='default_description_for_items.publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='default_description_for_items.series')),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
