# Generated by Django 4.0.6 on 2022-07-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_book_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback')], max_length=30, verbose_name='Book type'),
        ),
        migrations.AlterField(
            model_name='book',
            name='instock',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=30, verbose_name='In stock'),
        ),
    ]
