# Generated by Django 4.0.6 on 2022-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_price_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
