# Generated by Django 4.0.6 on 2022-08-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_book_availible'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.book')),
            ],
            bases=('items.book',),
        ),
    ]
