# Generated by Django 4.0.6 on 2022-07-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_format_pages_yearofpublication_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='Print lenth')),
            ],
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.AlterField(
            model_name='yearofpublication',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Release'),
        ),
    ]
