# Generated by Django 4.0.6 on 2022-07-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_page_delete_pages_alter_yearofpublication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='cover',
            field=models.CharField(choices=[('Hard', 'Hardcover'), ('Soft', 'Paperback')], default='бука', max_length=30, verbose_name='Format'),
            preserve_default=False,
        ),
    ]
