# Generated by Django 4.0.6 on 2022-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Picture'),
        ),
    ]
