# Generated by Django 4.0.6 on 2022-07-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isbn',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
