# Generated by Django 4.0.6 on 2022-07-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_rename_isbn_isbn_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=30, verbose_name='In stock')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3, verbose_name='Reading Age')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Item weight')),
            ],
        ),
    ]
