# Generated by Django 4.0.6 on 2022-07-10 22:30

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_instock_readingage_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name of the item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Release')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='Print lenth')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Item weight')),
                ('cover', models.CharField(choices=[('Hard', 'Hardcover'), ('Soft', 'Paperback'), ('y', 'Yes'), ('n', 'No')], max_length=30, verbose_name='In stock')),
                ('age', models.CharField(max_length=3, verbose_name='Reading Age')),
                ('availible', models.PositiveIntegerField(verbose_name='Books availible')),
            ],
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='InStock',
        ),
        migrations.DeleteModel(
            name='ISBN',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ReadingAge',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.DeleteModel(
            name='YearOfPublication',
        ),
    ]
