# Generated by Django 4.0.6 on 2022-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='instock',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=';e', max_length=30, verbose_name='In stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('Hard', 'Hardcover'), ('Soft', 'Paperback')], max_length=30, verbose_name='Format'),
        ),
    ]
