# Generated by Django 4.0.6 on 2022-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_book_availible_alter_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(default='1', max_length=25, verbose_name='Dimensions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price(BYN)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Release year'),
        ),
    ]
