# Generated by Django 4.0.6 on 2022-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='itemincart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
